### ISSUE TITLE
Optimize build file process

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/starterkit#47]
Using [`gulp-changed`](https://www.npmjs.com/package/gulp-changed), modify the tasks at the [starterkit gulpfile.js](https://github.com/carloscuesta/starterkit/blob/master/gulpfile.js) to only build those files that have been changed.

To Do:
- [ ] Add `gulp-changed` as a devDependecy.
- [ ] Require gulp-changed in `gulpfile.js`
- [ ] Update tasks: `styles`, `scripts`, `templates`

⚠️ **Test the behavior when changing pug `_file.pug` includes.**

**Comment by SergiSMJ** [comment]
I'm working on it! ;)
