### ISSUE TITLE
Gulp Critical task does not wokr

### ISSUE THREAD

**Issue by valeriosillari** [carloscuesta/starterkit#57]
Got a problem with Gulp critical task.

Clone the repo >> run npm install >> run gulp default task >> Everything is ok and working.

then locally run command "gulp critical" just for testing

here got an erro in CLI:

TypeError: (0 , _critical2.default) is not a function
    at Gulp.<anonymous> (/Users/MYNAME/MYFOLDER/starterkit/gulpfile.babel.js:247:9)
    at module.exports 

....

did i do something wrong?
or is there is a bug?

help :)

**Comment by hnnngb** [comment]
I get the same error as @valeriosillari 
when I use `var critical = require('critical').stream;`
everything works fine.

**Comment by carloscuesta** [comment]
Just added `.stream` to the critical pipe, thanks @henningbe.
