### ISSUE TITLE
Uncaught ReferenceError: require is not defined on ES6 Import of node module

### ISSUE THREAD

**Issue by GrahamWilsdon** [carloscuesta/starterkit#64]
Getting an reference error error when I try to import any ES6 module in index.js

`import LazyLoad from "vanilla-lazyload";`

(This is a terrific project, easy to fall out of touch when you are always using the create react app cli!)

**Comment by fcojgodoy** [comment]
Maybe it has something to do with [this issue](https://github.com/carloscuesta/starterkit/issues/65)

**Comment by carloscuesta** [comment]
Hey!

Completely missed these issue, I'll close this as I've stopped maintaining this for a while now.

Thanks for using this! ❤️
